- name: Base System Setup
  hosts: all
  become: true
  tasks:
    - name: Update and upgrade system packages
      apt:
        update_cache: yes
        upgrade: dist
      notify:
        - Reboot if kernel updated

  handlers:
    - name: Reboot if kernel updated
      ansible.builtin.reboot:
        reboot_timeout: 300

